### ISSUE TITLE
Using DEqMS with some missing values

### ISSUE THREAD

**Issue by jesswhitts** [yafeng/DEqMS#21]
Hello, 

Is DEqMS suitable for handling missing values? 

I have pre-filtered my data, so that only peptides detected in 2 of 3 replicates per condition are used in the model. But fit3$count still contains NA values... Do I need to remove all NAs? This loses a lot of my data

Many thanks,
Jess

**Comment by lattaai10** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the DEqMS analysis process to handle missing values by removing NAs from fit3$count and updating the corresponding rows in the protein matrix. This ensures that proteins with missing values are properly handled without losing too much data.

You can review changes in this commit: https://github.com/lattaai10/yafeng-DEqMS-21/commit/17df04da62ee5e7c51aa57c18fb3d2063df56fd5.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jesswhitts** [comment]
This problem was solved by amending the psm.count.table generation, for some reason this incorporated the NAs as minimum values. 

I changed my code to this:

design <- model.matrix(~0+cond+batch)
colnames(design) <- gsub("cond","",colnames(design))
contrast <-  makeContrasts(contrasts=c,levels=design)
fit1 <- lmFit(df, design)
fit2 <- contrasts.fit(fit1,contrasts = contrast)
fit3 <- eBayes(fit2)
psm.count.table <- data.frame(count = rowMins(
  as.matrix(df_raw), na.rm = TRUE), row.names =  row.names(df_raw))
fit3$count <- psm.count.table[rownames(fit3$coefficients),"count"]
if (min(fit3$count)==0){
  fit3$count = fit3$count + 1
}
fit4 <- spectraCounteBayes(fit3)

I hope this makes sense @yafeng - thanks for your help!

**Comment by yafeng** [comment]
psm.count.table <- data.frame(count = rowMins(
as.matrix(df_raw), na.rm = TRUE),
It is important to add na.rm=T here to avoid introducing NAs in the PSM count table. This is how the NAs in the fit3$count introduced, I guess.

As for adding batch factor in the design table, it is OK if the batch effect was observed in your data.

The rest of codes look OK.

Yafeng

在 2024年11月14日，08:22，jesswhitts ***@***.***> 写道：

psm.count.table <- data.frame(count = rowMins(
as.matrix(df_raw), na.rm = TRUE),

**Comment by jesswhitts** [comment]
Great, thank you!
